#ifndef ch_bear_animations_h
#define ch_bear_animations_h

#include "animation.h"

#define CH_BEAR_ANIMATION_DEATH 0

#define CH_BEAR_ANIMATION_WALK 1

#define CH_BEAR_ANIMATION_ATTACK 2

#define CH_BEAR_ANIMATION_STATPONC 3

#define CH_BEAR_ANIMATION_STATICBASE 4

#define CH_BEAR_ANIMATIONS_COUNT 5

extern const Animation CH_BEAR_ANIMATIONS[];

#define CH_BEAR_ANIMATION_WIDTH 32
#define CH_BEAR_ANIMATION_HEIGHT 24
#define CH_BEAR_ANIMATION_CENTER_X 10
#define CH_BEAR_ANIMATION_CENTER_Y 16
#define CH_BEAR_ANIMATION_BOUNDS_X 1
#define CH_BEAR_ANIMATION_BOUNDS_Y 8
#define CH_BEAR_ANIMATION_BOUNDS_WIDTH 19
#define CH_BEAR_ANIMATION_BOUNDS_HEIGHT 16

#endif /* ch_bear_animations_h */
