#ifndef ch_hero_animations_h
#define ch_hero_animations_h

#include "animation.h"

#define CH_HERO_ANIMATION_DEATH 0

#define CH_HERO_ANIMATION_IMPACT_BOTTOM 1

#define CH_HERO_ANIMATION_IMPACT_TOP 2

#define CH_HERO_ANIMATION_IMPACT_BACK 3

#define CH_HERO_ANIMATION_IMPACT_FRONT 4

#define CH_HERO_ANIMATION_JUMPKICK 5

#define CH_HERO_ANIMATION_PUNCH 6

#define CH_HERO_ANIMATION_CROUNCH 7

#define CH_HERO_ANIMATION_RECEP 8

#define CH_HERO_ANIMATION_FALL 9

#define CH_HERO_ANIMATION_JUMP 10

#define CH_HERO_ANIMATION_RUNSTOP 11

#define CH_HERO_ANIMATION_RUN 12

#define CH_HERO_ANIMATION_WALK 13

#define CH_HERO_ANIMATION_STAT 14

#define CH_HERO_ANIMATIONS_COUNT 15

extern const Animation CH_HERO_ANIMATIONS[];

#define CH_HERO_ANIMATION_WIDTH 8
#define CH_HERO_ANIMATION_HEIGHT 8
#define CH_HERO_ANIMATION_CENTER_X 4
#define CH_HERO_ANIMATION_CENTER_Y 4
#define CH_HERO_ANIMATION_BOUNDS_X 1
#define CH_HERO_ANIMATION_BOUNDS_Y 0
#define CH_HERO_ANIMATION_BOUNDS_WIDTH 6
#define CH_HERO_ANIMATION_BOUNDS_HEIGHT 8

#endif /* ch_hero_animations_h */
