#ifndef ch_spider_small_animations_h
#define ch_spider_small_animations_h

#include "animation.h"

#define CH_SPIDER_SMALL_ANIMATION_SHOOTWEB 0

#define CH_SPIDER_SMALL_ANIMATION_DEATH 1

#define CH_SPIDER_SMALL_ANIMATION_JUMP 2

#define CH_SPIDER_SMALL_ANIMATION_WALK 3

#define CH_SPIDER_SMALL_ANIMATION_STAT 4

#define CH_SPIDER_SMALL_ANIMATIONS_COUNT 5

extern const Animation CH_SPIDER_SMALL_ANIMATIONS[];

#define CH_SPIDER_SMALL_ANIMATION_WIDTH 16
#define CH_SPIDER_SMALL_ANIMATION_HEIGHT 8
#define CH_SPIDER_SMALL_ANIMATION_CENTER_X 7
#define CH_SPIDER_SMALL_ANIMATION_CENTER_Y 4
#define CH_SPIDER_SMALL_ANIMATION_BOUNDS_X 1
#define CH_SPIDER_SMALL_ANIMATION_BOUNDS_Y 0
#define CH_SPIDER_SMALL_ANIMATION_BOUNDS_WIDTH 13
#define CH_SPIDER_SMALL_ANIMATION_BOUNDS_HEIGHT 8

#endif /* ch_spider_small_animations_h */
