#ifndef ch_spider_large_animations_h
#define ch_spider_large_animations_h

#include "animation.h"

#define CH_SPIDER_LARGE_ANIMATION_ATTACK 0

#define CH_SPIDER_LARGE_ANIMATION_WALK 1

#define CH_SPIDER_LARGE_ANIMATION_STAT 2

#define CH_SPIDER_LARGE_ANIMATION_RISE 3

#define CH_SPIDER_LARGE_ANIMATION_AWAKEN 4

#define CH_SPIDER_LARGE_ANIMATION_SLEEP 5

#define CH_SPIDER_LARGE_ANIMATIONS_COUNT 6

extern const Animation CH_SPIDER_LARGE_ANIMATIONS[];

#define CH_SPIDER_LARGE_ANIMATION_WIDTH 24
#define CH_SPIDER_LARGE_ANIMATION_HEIGHT 16
#define CH_SPIDER_LARGE_ANIMATION_CENTER_X 10
#define CH_SPIDER_LARGE_ANIMATION_CENTER_Y 8
#define CH_SPIDER_LARGE_ANIMATION_BOUNDS_X 1
#define CH_SPIDER_LARGE_ANIMATION_BOUNDS_Y 0
#define CH_SPIDER_LARGE_ANIMATION_BOUNDS_WIDTH 18
#define CH_SPIDER_LARGE_ANIMATION_BOUNDS_HEIGHT 16

#endif /* ch_spider_large_animations_h */
