#ifndef player_animations_h
#define player_animations_h

#include "animation.h"

#define PLAYER_ANIMATION_DEATH 0

#define PLAYER_ANIMATION_IMPACT_BOTTOM 1

#define PLAYER_ANIMATION_IMPACT_TOP 2

#define PLAYER_ANIMATION_IMPACT_BACK 3

#define PLAYER_ANIMATION_IMPACT_FRONT 4

#define PLAYER_ANIMATION_JUMPKICK 5

#define PLAYER_ANIMATION_PUNCH 6

#define PLAYER_ANIMATION_CROUCH 7

#define PLAYER_ANIMATION_RECEP 8

#define PLAYER_ANIMATION_FALL 9

#define PLAYER_ANIMATION_JUMP 10

#define PLAYER_ANIMATION_RUNSTOP 11

#define PLAYER_ANIMATION_RUN 12

#define PLAYER_ANIMATION_WALK 13

#define PLAYER_ANIMATION_STAT 14

#define PLAYER_ANIMATIONS_COUNT 15

extern const Animation PLAYER_ANIMATIONS[];

#endif /* player_animations_h */
