#ifndef IMAGES_H
#define IMAGES_H

#include "animation.h"

#define ANIMATION_DEATH 0

#define ANIMATION_IMPACT_BOTTOM 1

#define ANIMATION_IMPACT_TOP 2

#define ANIMATION_IMPACT_BACK 3

#define ANIMATION_IMPACT_FRONT 4

#define ANIMATION_KICK 5

#define ANIMATION_PUNCH 6

#define ANIMATION_CROUCH 7

#define ANIMATION_RECEP 8

#define ANIMATION_FALL 9

#define ANIMATION_JUMP 10

#define ANIMATION_RUN_STOP 11

#define ANIMATION_RUN 12

#define ANIMATION_WALK 13

#define ANIMATION_STAT_1 14

#define ANIMATION_STAT_2 15

#define ANIMATION_STAT_3 16

#define ANIMATIONS_COUNT 17

extern const Animation animations[];

#endif // IMAGES_H
